### PR TITLE
Row and col span support

### PR DESCRIPTION
**Pull request by areinmeyer**
#10 Added support for rowspan and colspan in xlsx conversion.  A test file was added to the repo that is not referenced but is an example of a complex Excel file used in testing (has rowspan & colspan individually as well as a combined cell example).

### CODE REVIEW

**Comment by pofider** [comment]
That is fantastic! Thank you.

Only remove the `"postinstall": "node lib/prepareScripts.js"` from the `package.json` please. The final scripts are part of the npm - see [here](https://github.com/pofider/html-to-xlsx/blob/master/lib/scripts/.npmignore#L1)

**Comment by areinmeyer** [comment]
Thanks for the feedback!  I removed the postinstall script.

**Comment by pofider** [comment]
Hm, I don't get why the travis fails, I merge this and fix it in master.

Thank you for you work

**Comment by areinmeyer** [comment]
Thanks!  I was just looking at why it was failing.  Maybe has to do with the node version?  But if you got it working that's great.

**Comment by pofider** [comment]
Yes it was node.js version problem.

**Pull request merged**
